### ISSUE TITLE
Send to Matt for Edits 

### ISSUE THREAD

**Issue by anncalderon** [HarvardForest/gv-enm#28]

**Comment by anncalderon** [comment]
[SDMResearchProposal.docx](https://github.com/HarvardForest/gENM/files/301495/SDMResearchProposal.docx)

@MKLau I am uploading my proposal here becuase for whatever reason, git still keeps trying to add all those data files even though I've already moved them to the "docs" folder.

**Comment by MKLau** [comment]
No worries, we can fix that tomorrow, or check out this instruction page:

http://stackoverflow.com/questions/1274057/making-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

Basically, you can do:

git rm --cached .

**Comment by MKLau** [comment]
Just took a quick look at the proposal and it's a really good start. Let's chat a bit about it first thing tomorrow. Re-arranging the sentences on the conceptual modeling and adding some summary sentences would make the abstract complete and form a firm basis for the rest of the proposal.
