### ISSUE TITLE
Work through RDATATRACKER tutorial 

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/gv-enm#38]
harvardforest.fas.harvard.edu:8080/exist/apps/datasets/showData.html?id=hf091

**Comment by anncalderon** [comment]
[ddg.txt](https://github.com/HarvardForest/gENM/files/314997/ddg.txt)

I didn't know how to get you the actual flow chart from DDG Explorer, but that is the text file.

**Comment by MKLau** [comment]
Just rendered the DDG in the DDGexplorer. Here's a screen grab of part of it. 

Let's maybe spend an hour or so on Thursday (tomorrow) working on this.

![screen shot 2016-06-15 at 11 04 19 am](https://cloud.githubusercontent.com/assets/5342857/16085252/6f9d1214-32e9-11e6-97b8-68e8bc2ef19d.png)
