### ISSUE TITLE
Check if Anna can attend the RDataTracker workshop at the Dataverse meeting

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/gv-enm#42]

**Comment by MKLau** [comment]
Registration is open and free!
http://projects.iq.harvard.edu/dcm2016/event-registration

http://projects.iq.harvard.edu/dcm2016/meeting-agenda

**Comment by MKLau** [comment]
@anncalderon check your schedule and check in with Dev.

**Comment by MKLau** [comment]
If so, let margo know @anncalderon is coming.

**Comment by anncalderon** [comment]
Got the okay on Manisha's part, Margot knows I'm coming, and I just finished registering!
