### ISSUE TITLE
Pacman fails to load

### ISSUE THREAD

**Issue by anncalderon** [HarvardForest/gv-enm#48]
> pacman::p_load(packs)
> Installing package into ‘/Users/annacalderon/Library/R/3.2/library’
> (as ‘lib’ is unspecified)
> Warning messages:
> 1: In p_install(package, character.only = TRUE, ...) : packs
> 2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
>   there is no package called ‘packs’
> 3: In pacman::p_load(packs) : Failed to install/load:
> packs

See this for a solution:

https://cran.r-project.org/web/packages/pacman/vignettes/Introduction_to_pacman.html

**Comment by MKLau** [comment]
Replacing pacman with lapply and installed.packages
