### ISSUE TITLE
negative value warning from cost-distance function in gClust

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/gv-enm#95]

**Comment by MKLau** [comment]
Warning message:                                                                       |                                        # default this is set to one for mathematical  
 In .TfromR(x, transitionFunction, directions, symm) :                                  |                                        # convenience. The diagonal is set to zero  
   transition function gives negative values

**Comment by anncalderon** [comment]
![uploads/3c1c739c-5e95-4d77-b796-a64ba575f31e/Screen Shot 2016-07-18 at 1.10.05 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F3c1c739c-5e95-4d77-b796-a64ba575f31e%2FScreen+Shot+2016-07-18+at+1.10.05+PM.png)

**Comment by MKLau** [comment]
Well, that's good!
