### ISSUE TITLE
gEanalysis function

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/gv-enm#97]

**Comment by anncalderon** [comment]
My loop for gAnalysis isn't working correctly. Will plot the first two cluster maps, but not the third or fourth. Plotted 3 and 4 outside the loop for now. 

for(i in 1: length(analysis)){zoom(analysis[[2]][[i]]$pred, ext=extent(-73.70833, -66.95833, 41, 47.45833),
         xaxt='n', yaxt='n', new=FALSE)}

**Comment by MKLau** [comment]
Check that mfrow in par() is creating enough panels in the the plot. That is, if you want to plot n plots, you need the product of the mfrow values to be equal to or greater than n. E.g. for 7 plots,

par(mfrow=c(4,2))
