### ISSUE TITLE
Does the transition matrix "wrap" around the edge of the map?

### ISSUE THREAD

**Issue by MKLau** [HarvardForest/gv-enm#99]

**Comment by anncalderon** [comment]
![uploads/0146ada1-fd91-403c-ac54-5b4d1d0ef1e6/Screen Shot 2016-07-18 at 1.23.49 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F0146ada1-fd91-403c-ac54-5b4d1d0ef1e6%2FScreen+Shot+2016-07-18+at+1.23.49+PM.png)

![uploads/c7be29d1-082c-49ab-8ccd-c1a987af9371/Screen Shot 2016-07-18 at 1.23.43 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fc7be29d1-082c-49ab-8ccd-c1a987af9371%2FScreen+Shot+2016-07-18+at+1.23.43+PM.png)

**Comment by anncalderon** [comment]
I guess the short answer is no. I don't think we have to worry about this becuase our coordinates don't touch each other (i.e: cover the entire globe). What do you think?

**Comment by MKLau** [comment]
I don't understand what it means to "reach across the globe" though. Is it defined in another part of the vignette?

**Comment by anncalderon** [comment]
I did a search, and that's the only part where they mention that statement. The way I understood it is if we don't have coordinates that encompass the entire globe, then the cells on the right won't be connected to the cells on the left. But, perhaps I'm misunderstanding it as well.

**Comment by anncalderon** [comment]
actually, I was confused as I was examining figure 3. To me, I don't see how the upper left corner is connected to more than 3 cells.

**Comment by MKLau** [comment]
Yeah, I'm not sure if it means the literal globe (i.e. the earth) or if it is referring to some characteristic defined as the "globe" in the context of a particular map. What's this doc that you're looking at again?
